
CREATE TABLE CONTACT (
	CONTACT_ID INT IDENTITY(1200, 1) NOT NULL,
	PHONE_NUMBER BIGINT NOT NULL,
	EMAIL NVARCHAR(50) NOT NULL,
	TITLE_ID INT
);

CREATE TABLE CO_ADVISER (
	CO_ID INT IDENTITY(800, 1) NOT NULL,
	LAST_NAME NVARCHAR(50) NOT NULL,
	FIRST_NAME NVARCHAR(50) NOT NULL,
	MIDDLE_NAME NVARCHAR(50) NOT NULL,
	TITLE_ID INT
);

CREATE TABLE ADVISER (
	ADVISER_ID INT IDENTITY(600, 1) NOT NULL,
	LAST_NAME NVARCHAR(50) NOT NULL,
	FIRST_NAME NVARCHAR(50) NOT NULL,
	MIDDLE_NAME NVARCHAR(50) NOT NULL,
	TITLE_ID INT
);

CREATE TABLE AUTHOR (
	AUTHOR_ID INT IDENTITY(400, 1) NOT NULL,
	LAST_NAME NVARCHAR(50) NOT NULL,
	FIRST_NAME NVARCHAR(50) NOT NULL,
	MIDDLE_NAME NVARCHAR(50) NOT NULL,
	TITLE_ID INT
);

CREATE TABLE TITLE (
	TITLE_ID INT IDENTITY(200, 1) NOT NULL,
	TITLE_NAME TEXT NOT NULL,
	PROGRAM NVARCHAR(50) NOT NULL,
	CO_PROGRAM NVARCHAR(50),
	SCHOOL_YEAR NVARCHAR(10) NOT NULL,
	DATE_OF_SUBMISSION DATETIME NOT NULL,
	SUBJECT NVARCHAR(50) NOT NULL
);